config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  get '/:locale', to: 'home#index', as: 'root_locale', :format => false, defaults: { locale: 'en' }
  root to: "home#index", defaults: { locale: 'bg' }

  scope "(:locale)", locale: /en|bg/ do
    resources :forms
    resources :tickets
    resources :contacts

    get '/:friendly_id', to: 'static_pages#show', as: 'static_page', :format => false
  end

  post '/tinymce_assets', to: 'tinymce_assets#create'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	apply_simple_captcha

	validates_each :email do |record, attr, value|
    	record.errors.add(attr, I18n.t(:invalidemail)) unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  	end

	validates :names, presence: true
	validates :message, presence: true
end

app/models/document.rb
class Document < ActiveRecord::Base

	STORE_DIR = 'documents'
	STORE_PATH = File.join("public", STORE_DIR)
	Dir.mkdir(STORE_PATH) unless Dir.exists?(STORE_PATH)
	
	belongs_to :static_page

	validates :name, presence: true, uniqueness: true
	validates :location, presence: true, uniqueness: true
	validates :doc_type, presence: true
	validates :static_page, presence: true

	def file= file
		self.doc_type = file.original_filename.split('.').last
		File.open(File.join(STORE_PATH, file.original_filename), "wb") { |f| f.write(file.read) }
		self.location = File.join(STORE_DIR, file.original_filename)
	end
end

app/models/form.rb
class Form < ActiveRecord::Base
	translates :description

	apply_simple_captcha

	belongs_to :university

	validates_each :email do |record, attr, value|
    	record.errors.add(attr, I18n.t(:invalidemail)) unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  	end

  	validates_each :mobile do |record, attr, value|
    	record.errors.add(attr, I18n.t(:invalidmobile)) unless value =~ /^[0-9]{10}$/
  	end
	validates :last_name, presence: true
	validates :first_name, presence: true
	validates :fathers_name, presence: true
	validates :birthday, presence: true
	validates :place_of_birth, presence: true
	validates :mobile, presence: true
	validates :skype, presence: true
	validates :university_id, presence: true
	validates :year_of_study, presence: true
	validates :email, presence: true
	validates :fletcher_office, presence: true

end

app/models/form_description.rb
class FormDescription < ActiveRecord::Base
	translates :body

	validates :body_en, presence: true
	validates :body_bg, presence: true
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title_en, :use => [:slugged, :finders]
	translates :title, :body
	
	validates :title_en, presence: true, uniqueness: true
	validates :title_bg, presence: true, uniqueness: true
	validates :body_en, presence: true
	validates :body_bg, presence: true
	validates :slug, presence: true, uniqueness: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

	validates_each :email do |record, attr, value|
    	record.errors.add(attr, I18n.t(:invalidemail)) unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  	end

  	validates_each :mobile do |record, attr, value|
    	record.errors.add(attr, I18n.t(:invalidmobile)) unless value =~ /^[0-9]{10}$/
  	end
	validates :last_name, presence: true
	validates :first_name, presence: true
	validates :birthday, presence: true
	validates :passport_num, presence: true
	validates :passport_valid_date, presence: true
	validates :email, presence: true
	validates :mobile, presence: true
	validates :destination, presence: true
	validates :departure_date, presence: true
	validates :comeback_date, presence: true
	validates :airlines, presence: true
	validates :arrival_time, presence: true
end

app/models/university.rb
class University < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true

	has_many :forms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :get_static_pages, :set_locale

  def get_static_pages
  	@pages = StaticPage.order(id: :asc)
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options #{options.inspect}\n"
    { locale: I18n.locale}
  end

  def set_locale
  	I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :set_locale

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(form_params)

		if @contact.valid_with_captcha?
			@contact.save
			FormMailer.contact_email(@contact).deliver
			flash[:notice] = t(:contact_form_success)
			redirect_to root_path
		else
			render 'new'
		end
	end

	private 
	def form_params
		params.require(:contact).permit(:names, :email, :message, :captcha, :captcha_key)
	end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :set_locale

	def new
		@static_pages = StaticPage.all
		@document = Document.new
	end

	def index
		@documents = Document.all
	end

	def create
		@document = Document.new params
		redirect_to admin_documents_path
	end

	def update
		@static_pages = StaticPage.all
		@document = Document.find(params[:id])

	end

	def destroy
		@document = Document.find(params[:id])
		if @document.destroy
			flash[:notice] = "Document deleted"
		else
			flash[:warning] = "Document not deleted"
		end
		redirect_to documents_path
	end

	private 

		def doc_params
			params.require(:document).permit :name, :location, :doc_type, :static_page_id
		end
	
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
	before_action :set_locale

	def new
		@formd = FormDescription.first
		@universities = University.all
		@form = Form.new
	end

	def create
		@universities = University.all
		@formd = FormDescription.first
		@form = Form.new(form_params)

		if @form.valid_with_captcha?
			@form.save
			FormMailer.application_email(@form).deliver
			FormMailer.application_email_to_employee(@form).deliver
			flash[:notice] = t(:form_success)
			redirect_to root_path
		else
			render 'new'
		end
	end

	private 
	def form_params
		params.require(:form).permit(:last_name, :first_name, :fathers_name, :birthday, :place_of_birth, :mobile, :skype, :university_id, :year_of_study, :email, :fletcher_office, :application_form_assistance, :job_offer_precheck, :ds_assistance, :captcha, :captcha_key)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :set_locale
	def show
		@page = StaticPage.friendly.find(params[:friendly_id])
		@header = Document.where(static_page_id: @page, doc_type:"jpg").first
	end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	def new
		#@formd = FormDescription.first
		@ticket = Ticket.new
	end

	def create
		#@formd = FormDescription.first
		@ticket = Ticket.new(ticket_params)

		if @ticket.save
			TicketMailer.ticket_email(@ticket).deliver
			flash[:notice] = I18n.t(:ticket_success)
			redirect_to root_path
		else
			render 'new'
		end
	end

	private 
	def ticket_params
		params.require(:ticket).permit(:first_name, :last_name, :birthday, :passport_num, :passport_valid_date, :email, :mobile, :destination, :departure_date, :comeback_date, :airlines, :arrival_time, :comments)
	end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController

  def create
    # Take upload from params[:file] and store it somehow...
    # Optionally also accept params[:hint] and consume if needed
    dirname = 'tinymce_assets'
    name = params[:file].original_filename

    Dir.mkdir("public/images/") unless Dir.exists?("public/images/")
	  Dir.mkdir("public/images/#{dirname}") unless Dir.exists?("public/images/#{dirname}")
	  filepath = "public/images/#{dirname}"

    path = File.join(filepath, name)
    File.open(path, "wb") { |f| f.write(params[:file].read) }
    image = dirname + '/' + name

    render json: {
      image: {
        url: view_context.image_url(image)
      }
    }, content_type: "text/html"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="banner">
	<%= image_tag "form_header.jpg" %>
</div>
<div class="content">	
	<h1><%= t(:contact_form) %></h1>
	<%= form_for @contact, url: contacts_path do |f| %>
		<% if @contact.errors.any? %>
			<ul>
				<% @contact.errors.full_messages.each do |msg| %>
				<li class="error-message"><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		<p>&nbsp;</p>
		<div class=".clearfix"></div>
</div>
<div class="form">
	<div>
		<p>
			<%= f.label t(:names) %><br/>
			<%= f.text_field :names %><br/>
		</p>
		<p>
			<%= f.label t(:email) %><br/>
			<%= f.text_field :email %><br/>
		</p>
		<p>
			<%= f.label t(:message) %><br/>
			<%= f.text_field :message %><br/>
		</p>
	</div>
	<%= show_simple_captcha(:object=>"contact") %>
	<div class="submit">
		<%= f.submit t(:submit_form), id: "submit-button" %>
	</div>
</div>
<% end %>

app/views/documents/index.html.erb
<ul>
	<% @documents.each do |d| %>
	<li>Document name: <%= d.name %></li>
	<li>Document location: <%= d.location %></li>
	<li>Document type: <%= d.doc_type %></li>
	<li>Document parent page: <%= d.static_page.title %></li>
	<li>end</li>
	<br/>
	<%= link_to "Delete document", d, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
</ul>

app/views/documents/new.html.erb
<h1>Document upload</h1>
<p>just some test here</p>
<%= form_for @document, url: documents_path do |f| %>
	<% if @document.errors.any? %>
		<ul>
			<% @document.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>
	<%= f.label :location %><br/>
	<%= f.file_field :location %><br/>
	<%= f.label :static_page_id %><br/>
	<%= collection_select(:document, :static_page_id, @static_pages, :id, :title, prompt: true) %><br/>
	<%= f.submit %>
<% end %>

app/views/forms/new.html.erb
<div class="banner">
	<%= image_tag "form_header.jpg" %>
</div>
<div class="content">	
	<h1><%= t(:app_form) %></h1>
	<p><%= @formd.body.html_safe %></p>
	<%= form_for @form, url: forms_path do |f| %>
		<% if @form.errors.any? %>
			<ul>
				<% @form.errors.full_messages.each do |msg| %>
				<li class="error-message"><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		<p>&nbsp;</p>
		<div class=".clearfix"></div>
</div>
<div class="form">
	<div>
		<p>
			<%= f.label t(:first_name) %><br/>
			<%= f.text_field :first_name %><br/>
		</p>
		<p>
			<%= f.label t(:fathers_name) %><br/>
			<%= f.text_field :fathers_name %><br/>
		</p>
		<p>
			<%= f.label t(:last_name) %><br/>
			<%= f.text_field :last_name %><br/>
		</p>
		<p class="date" style="width: 370px;">
			<%= f.label t(:birthday) %><br/>
			<%= date_select :form, :birthday, start_year: Time.now.year - 35, end_year: Time.now.year - 18 %><br/>
		</p>
		<p>
			<%= f.label t(:place_of_birth) %><br/>
			<%= f.text_field :place_of_birth %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:mobile) %><br/>
			<%= f.text_field :mobile %><br/>
		</p>
		<p>	
			<%= f.label t(:skype) %><br/>
			<%= f.text_field :skype %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:university) %><br/>
			<%= collection_select(:form, :university_id, @universities, :id, :name, prompt: true) %><br/>
		</p>
		<p>
			<%= f.label t(:year_of_study) %><br/>
			<%= select "form", "year_of_study", [ ["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["master 1", "master 1"], ["master 2", "master 2"], ["master 3", "master 3"], ["master 4", "master 4"], ] %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:email) %><br/>
			<%= f.text_field :email %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:fletcher_office) %><br/>
			<%= select "form", "fletcher_office", [[ "Sofia", "Sofia" ], [ "Blagoevgrad", "Blagoevgrad" ]] %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:application_form_assistance), class:"title" %>
			<description>
				<%= t(:application_form_assistance_description) %>
				<br/><br/>
			</description>
			<%= select "form", "application_form_assistance", [[t(:answer1), t(:answer1)], [t(:answer2), t(:answer2)], [t(:answer3), t(:answer3)]] %><br/>
		</p>
		<p>
			<%= f.label t(:job_offer_precheck), class:"title" %>
			<description>
				<%= t(:job_offer_precheck_description) %>
				<br/><br/>
			</description>
			<%= select "form", "job_offer_precheck", [[t(:answer1), t(:answer1)], [t(:answer2), t(:answer2)], [t(:answer3), t(:answer3)]] %>
		</p>
		<p>
			<%= f.label t(:ds_assistance), class:"title" %>
			<description>
				<%= t(:ds_assistance_description) %>
				<br/><br/><br/>
			</description>
			<%= select "form", "ds_assistance", [[t(:answer1), t(:answer1)], [t(:answer2), t(:answer2)], [t(:answer3), t(:answer3)]] %>
		</p>
	</div>
	<%= show_simple_captcha(:object=>"form") %>
	<div class="submit">
		<%= f.submit "Submit", id: "submit-button" %>
	</div>
</div>
<% end %>

app/views/forms/old.html.haml
- form_for @form, url: forms_path do |f|
	= if @form.errors.any?
		= pluralize(@form.errors.count 'error')
		'prohibited this form from being saved'
		%ul
			- @form.errors.full_messages.each do |msg|
				%li 
					= msg
	= f.label :last_name
	= f.text_field :last_name
	= f.label :first_name
	= f.text_field :first_name
	= f.label :fathers_name
	= f.text_field :fathers_name
	= f.label :birthday
	= f.text_field :birthday
	= f.label :place_of_birth
	= f.text_field :place_of_birth
	= f.label :mobile
	= f.text_field :mobile
	= f.label :skype
	= f.text_field :skype
	= f.label :university
	= f.text_field :university
	= f.label :year_of_study
	= f.text_field :year_of_study
	= f.label :email
	= f.text_field :email
	= f.label :fletcher_office
	= f.text_field :fletcher_office
	= f.submit

app/views/home/index.html.haml
.banner
  .bannerText.clearfix
    %p
      $498
    %div
      %p
        Low cost
      %p
        Work and Travel
%section
  %div
    %a#terms-and-conditions
      = t(:terms_and_conditions)
  %div
    %a#apply-online
      = t(:apply_online)
  %div
    %a#tax-refund
      = t(:tax_refund)

app/views/layouts/_footer.html.haml
%footer
  %h2
    = t(:contacts)
  %table
    %tr
      %td
        %span
          = t(:sofia)
        %br
        %span
          = t(:gurko)
        %br
        %span
          = t(:sof_phones)
        %br
        %a{href: "mailto:info@fletcherlynd.com", target: "_top"}
          info@fletcherlynd.com
      %td
        %span
          = t(:blagoevgrad)
        %br
        %span
          = t(:alexandrov)
        %br
        %span
          = t(:bl_phones)
        %br
        %a{href: "mailto:blagoevgrad@fletcherlynd.com", target: "_top"}
          blagoevgrad@fletcherlynd.com
  .bottomSocial
    %a{href: "mailto:info@fletcherlynd.com", target: "_top"}
    %a
    %a
  %a{href:"http://fletcherlynd.com", target:"_blank"}

%script
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57005313-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_head.html.haml
%head
    %meta{:charset => "utf-8"}
    %title Low Cost Work and Travel - Fletcher Lynd – J1 Visa – Студентски Бригади САЩ
    %meta{:content => "user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi", :name => "viewport"}
    %meta{:content => "", :name => "Fletcher Lynd Site"}
    %meta{:content => "", :name => "BetaSve.com"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
    = favicon_link_tag 'favicon.ico'
    = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    %header
      .clearfix
        = link_to(image_tag("logo.png"), root_path)
        %a#menuButton
          &nbsp;
        .rightMenu
          %a{href:"mailto:info@fletcherlynd.com"}
          %a
            &nbsp;
          %a
            &nbsp;
          %div
            = link_to "EN", root_locale_path
            |
            = link_to "BG", root_locale_path('bg')
          %a{href: "http://fletcherlynd.com/", target: "_blank"}
        %nav#menu
          %ul
            - if params[:locale] == 'bg'
              = link_to t(:home), root_locale_path('bg')
            -else
              = link_to t(:home), root_path
            - @pages.each_with_index do |page, k|
              = link_to page.title, static_page_path(friendly_id: page.slug)
              = link_to t(:apply_online), new_form_path if k == 0
            = link_to t(:contacts), new_contact_path
    .space
    - flash.each do |name, msg|
      = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable" do
        %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
        %p
          = msg
    = yield
    = render 'layouts/footer'

app/views/layouts/old_application.html.erb
    .navbar.navbar-inverse.navbar-fixed-top      
      .container
        .navbar-header
          %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => ".navbar-collapse"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Fletcher Lynd", root_path, :class => "navbar-brand"
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to t(:home), root_path
            - @pages.each do |page|
              %li
                = link_to page.title, static_page_path(friendly_id: page.slug)
            %li
              = link_to t(:form), new_form_path, "data-no-turbolink" => true, class: ".empty"
            %li
              = link_to t(:ticket), new_ticket_path  
          .pull-right
            %ul.nav.navbar-nav
              %li
                = link_to "en", root_locale_path
              %li
                = link_to "bg", root_locale_path('bg')

app/views/simple_captcha/_simple_captcha.erb
<div>
  <span class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
    <br/>
    <%= simple_captcha_options[:field] %>
    <br/>
    <%= simple_captcha_options[:refresh_button] %>
  </span>
</div>

app/views/static_pages/show.html.haml
- if @header
	.banner
		%img{src: "/#{@header.location}"}
.content
	%h1
		= @page.title
	.text
		= @page.body.html_safe

app/views/tickets/new.html.haml
= form_for @ticket, url: tickets_path do |f|
	= if @ticket.errors.any?
		= pluralize(@ticket.errors.count 'error')
		'prohibited this form from being saved'
		%ul
			- @ticket.errors.full_messages.each do |msg|
				%li 
					= msg
	
	= f.label t(:first_name)
	%br
		= f.text_field :first_name
	
	= f.label t(:last_name)
	%br 
		= f.text_field :last_name
	
	= f.label t(:birthday)
	%br
		= date_select :ticket, :birthday, start_year: Time.now.year - 30, end_year: Time.now.year - 18
	
	= f.label t(:passport_num)
	%br
		= f.text_field :passport_num
	
	= f.label t(:passport_valid_date)
	%br
		= date_select :ticket, :passport_valid_date, start_year: Time.now.year, end_year: Time.now.year + 10 
	
	= f.label t(:email)
	%br
		= f.text_field :email
	
	= f.label t(:mobile)
	%br
		= f.text_field :mobile
	
	= f.label t(:destination)
	%br
		= f.text_field :destination
	
	= f.label t(:departure_date)
	%br
		= date_select :ticket, :departure_date, start_year: Time.now.year, end_year: Time.now.year + 3
	
	= f.label t(:comeback_date)
	%br
		= date_select :ticket, :comeback_date, start_year: Time.now.year, end_year: Time.now.year + 5
	
	= f.label t(:airlines)
	%br
		= f.text_field :airlines
	
	= f.label t(:arrival_time)
	%br
		= f.text_field :arrival_time
	
	= f.label t(:comments)
	%br
		= f.text_area :comments
	= f.submit